[package]
authors = ["Cylonix authors <contact@cylonix.io>"]
build = "build.rs"
edition = "2018"
link = "wg"
name = "wg-sys"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[build-dependencies]
cc = "1.0.72"
